name: API Specs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - name: No Operation
        run: echo "This job does nothing."

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: No Operation
        run: echo "This job does nothing."
